### ISSUE TITLE
Allow build commands as well as scripts

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/bunny-hook#2]
Many of the builds I run (e.g. for static sites) involve just a handful of commands, so a full build script is overkill. It'd be nice to alter the `deploy.yml` parser to accept a directive to run build commands in addition to build scripts, something like:

```yaml
build:
    - command:
        - echo "Running build script"
        - echo "Done running script"
    - script:
        - scripts/build.sh
```
